### PR TITLE
Laravel 8 Support with Travis

### PR DESCRIPTION
**Pull request by jdavidbakr**
## Goal

Add support for Laravel 8

## Design

Added travis tests (extended from PR https://github.com/bugsnag/bugsnag-laravel/pull/405)

## Changeset

Tests added to Travis

## Testing

No additional tests were required

### CODE REVIEW

**Comment by jdavidbakr** [comment]
For some reason it looks like composer is broken, I couldn't reproduce the issue in Travis until I updated my local composer from 1.10.7 to 1.10.11

**Comment by jdavidbakr** [comment]
https://github.com/composer/composer/issues/9191

**Comment by jdavidbakr** [comment]
Composer has been patched, resubmitting the build

**Comment by jwpage** [comment]
Thanks for adding in the Travis changes I overlooked 👍

**Review by imjoehaines — APPROVED** [review]
Thanks @jwpage & @jdavidbakr!

**Review by dacoto97 — APPROVED** [review]

**Comment by dacoto97** [comment]
Hi @imjoehaines.
What is the estimated release date for the version with support for laravel 8?
Thanks!

**Comment by imjoehaines** [comment]
> Hi @imjoehaines.
> What is the estimated release date for the version with support for laravel 8?
> Thanks!

Hey, I'm aiming for a release either this afternoon or tomorrow

**Pull request merged**
