### PR TITLE
Fixed determining the builder name

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Depends on https://github.com/bugsnag/bugsnag-php/pull/572. Closes https://github.com/bugsnag/bugsnag-laravel/issues/369.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Well, the PHP notifier still doesn't depend on symfony. It just uses it if it's available. We could actually delete the symfony code entirely if we really wanted.

**Comment by tomlongridge** [comment]
OK, not depend in the Composer sense but I would say for the `bugsnag-php` library to reference any framework-specific code should be avoided. I don't want to cause a breaking change by removing it - I was anticipating fixing the include path and maybe adding a test of when `Process` class doesn't exist (do we even support a version of Laravel when this doesn't exist?)

**Comment by GrahamCampbell** [comment]
I wouldn't say deleting this code is a breaking change. It's just the internals of the library. We were not getting the process class instance from the container, so users had no opportunity to mess with it.

**Comment by snmaynard** [comment]
I would generally favor an approach that means we have bugsnag-php that includes plugins for all the php frameworks we want to support. This is how ruby/python work and it means we don't have dependency issues. If that is the way it could be built, I would be generally supportive of that - cc @kattrali

**Comment by tomlongridge** [comment]
We've discussed this and agreed that there's no need for the Symfony code as there's no reason the native way of executing process calls wouldn't work. So we can merge this and close bugsnag/bugsnag-php#572.

**Pull request merged**
