### PR TITLE
Laravel 5

### PR DESCRIPTION
**Pull request by ConradIrwin**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please exclude the examples from the dist download by setting the correct stuff in the .gitattributes file.

**Comment by ConradIrwin** [comment]
Thanks @GrahamCampbell, does that look better to you?

**Comment by GrahamCampbell** [comment]
And yeh, that's much better. :)

**Comment by loopj** [comment]
:penguin: elegant solution

**Pull request merged**
