### PR TITLE
Enable Laravel 5.5 auto-discovery.

### PR DESCRIPTION
**Pull request by lucasmichot**
Enable Laravel 5.5 package auto-discovery:

---

See:

- https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518
- https://github.com/barryvdh/laravel-debugbar/pull/643

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
How do we enforce the service provider ordering we want? This provider must be registered before the app service provider.

**Comment by driesvints** [comment]
@GrahamCampbell I actually never do this and it works fine. Any specific reasons for this?

**Comment by driesvints** [comment]
If you need specific ordering of service providers you can't use auto-discovery btw. If you maintain a package that needs ordering just ask people to register the service provider like they do now.

**Comment by GrahamCampbell** [comment]
See https://github.com/bugsnag/bugsnag-laravel/issues/206.

**Comment by driesvints** [comment]
Ah, I guess it might be because we're using the multi logger? That could be it.

But yeah if you need ordering then you can't make use of the auto-discovery atm.

**Pull request closed without merging**
