### PR TITLE
Add package autodiscovery

### PR DESCRIPTION
**Pull request by joelclermont**
## Goal

Simplify package installation with service provider and alias auto discovery. Also has the nice side effect of minimizing customizations to the `config/app.php` file for consumers of this package.

### Added

New `extra.laravel` section in `composer.json`

## Tests

No changes to package behavior, so no tests included

## Review

For the submitter, initial self-review:

- [X] Commented on code changes inline explain the reasoning behind the approach (no comments in composer.json)
- [X] Reviewed the test cases added for completeness and possible points for discussion (no tests added)
- [X] A changelog entry was added for the goal of this pull request
- [X] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [ ] Initial review of the intended approach, not yet feature complete
  - [ ] Structural review of the classes, functions, and properties modified
  - [X] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR, however, Bugsnag cannot support this because it would result in Bugsnag being loaded too late by the framework. See https://github.com/bugsnag/bugsnag-laravel/pull/298.

**Comment by joelclermont** [comment]
Oh, that makes sense now, and sorry for not searching past PRs to see this had been tried before.

Is it crazy to wonder if we could possibly add some simple prioritization in auto-discovery such that auto-discovered providers get loaded before the `AppProvider`? I noticed there was a [discussion about a general strategy for ordering all providers](https://github.com/laravel/framework/issues/23174), and I agree that's way too complicated, but what do you think of my idea?

**Comment by joelclermont** [comment]
One more note, if you look at `config/app.php`, the `providers` key is already structured by default into three groups: framework, packages, and application. So having packages with auto-discovery loaded before the application service providers isn't different from what's already being recommend with explicit provider wiring.

**Comment by GrahamCampbell** [comment]
Automatic registration used to insert bugsnag too late in the chain. I've not tested the behaviour in the very latest version. Even then, bugsnag needs to work for all versions, so it would only be confusing to add even if it did put it above all the other packages

**Pull request closed without merging**
