### PR TITLE
Added Laravel 11 Support

### PR DESCRIPTION
**Pull request by jonathan-dij**
## Goal

To support Laravel 11

## Testing

By running the tests

### CODE REVIEW

**Comment by clr182** [comment]
Hi @jonathan-dij  

Thank you for opening this PR. 
Once Laravel 11 has been released we will review, confirm support with our system tests and merge this PR. Once we have more information we will be sure to update you.

**Comment by gabrielrbarbosa** [comment]
Laravel 11 is scheduled to release on Q1 2024, please merge this so we can also test our project with all packages as soon as possible!

**Comment by imjoehaines** [comment]
Hi @jonathan-dij, thanks for the PR

We don't usually release support for new Laravel versions until after they are released because of the risk of breaking changes being introduced late in Laravel's release cycle

We will merge and release this ASAP after Laravel 11 is officially released

In the meantime, you can test you app by [pointing Composer at your fork](https://stackoverflow.com/a/13500676) using [the `repositories` option](https://getcomposer.org/doc/04-schema.md#repositories)

**Comment by gabrielrbarbosa** [comment]
https://blog.laravel.com/laravel-11-now-available

**Review by imjoehaines — APPROVED** [review]

**Pull request merged**
